### ISSUE TITLE
Add Undo option

### ISSUE THREAD

**Issue by strayblues** [strayblues/mandala#10]

**Comment by rwmpelstilzchen** [comment]
I guess the easiest solution would be saving the image in a stack every time you release the mouse button after drawing. `undo() = pop()`.

**Comment by strayblues** [comment]
![Screen Shot 2020-12-06 at 17 15 56](https://user-images.githubusercontent.com/18241007/101284071-e2158900-37e6-11eb-9b22-7bccea59c4d8.png)
