### ISSUE TITLE
Put this up on GitHub pages

### ISSUE THREAD

**Issue by Niharika29** [strayblues/mandala#33]
I heard about this awesome thing from Moriel today and I wanted to play with it. :)
You should consider putting it up on [GitHub pages](https://pages.github.com) so people can use it. 

(Also, unrelated, .DS_STORE should probably not be in the repo)

**Comment by strayblues** [comment]
You can find it [here](http://mandala.hagarsh.com/).

**Comment by Niharika29** [comment]
Thanks! Please add it to the repo description too. :) Good job! It's super fun!

**Comment by strayblues** [comment]
Done. Thank you. :)

**Comment by rwmpelstilzchen** [comment]
I think this issue can be closed now.
